### ISSUE TITLE
Working with variants

### ISSUE THREAD

**Issue by michaelfeihstel** [ahl389/shopify-buy-sdk-example#2]
First of all thanks a lot for your work @ahl389 

I tried to work with your example and a collection of products that use variants. Did you test the example in such a scenario? As far as I can tell, and maybe my minor adjustments are to blame here, your code has some problems in the `attachOnVariantSelectListeners()` function. First it doesn't seem to get the `productID` which I fixed by changing the jquery lookup of `data-product-id` like this:

`var productID = element.closest('.product').attr('data-product-id');`

I think this easier to understand than chaining `.parent()`and `.next()` and it allows for a very flexible markup / layout within the product container as the data-product-id only needs to be present on the product div, regardless of the structure within that container.

Furthermore, and unless I'm missing something, the actual "Add To Cart"-button isn't updated with the new variant.id upon selection which results in the same product variant being added to the cart over and over again regardless of the actual selection. I'm looking into changing that right now and it should be an easy fix, but since I really don't like working in JS it may be a messy adventure for me.

Anyway, I just wanted to get a discussion going and see if this example actually has issues when working with variants or if I'm missing something.

**Comment by ahl389** [comment]
@michaelfeihstel thanks - I'll look at this today.  It was working A-OK, but my client requested some style modifications that resulted in me reworking the HTML structure a tad, and it's totally possible that something broke in that process.

**Comment by michaelfeihstel** [comment]
I'm sorry, I just noticed it was my mistake. You actually update the `data-variant-id`attribute of the buy button, but your selector was very dependent on the correct HTML structure and since I use a different structure it failed. And I failed to notice that line of code. Anyway, I just saw it and I suggest another change: I think it's a good idea to change the jquery selector in such a way that it doesn't matter where the add to cart button is positioned within the markup. I did this by only relying on a class name and the correct `data-product-id`, as in:

`$('.add-button[data-product-id="+ productID +"]').attr('data-variant-id', variant.id)`

**Comment by ahl389** [comment]
Nope that's okay - we were both half right.  The product ID was never getting stored because of my HTML structure changes, so the variant image, title, etc. were not being updated.  The correct variant was, however, being added to the cart like you mentioned.  I took your suggestion and changed the JS for capturing the productID and I like your note there on the product button.  I'll push these changes in the next hour!

**Comment by ahl389** [comment]
@michaelfeihstel  Awesome, done!
