### ISSUE TITLE
Clear cart after checkout integration  

### ISSUE THREAD

**Issue by zstrad44** [ahl389/shopify-buy-sdk-example#5]
This is in reference to an already open issue on the main Shopify-SDK [#98]
(https://github.com/Shopify/js-buy-sdk/issues/98). 

**To summarize the issue:** Currently, the cart doesn't clear itself when the user checks out.   

They gave a temp solution of using the ["Checkout example"](https://github.com/Shopify/js-buy-sdk/tree/master/examples/checkout) in the Shopify SDK repo. Which essentially will use event listeners to see if the user has completed the checkout process, then on event will clear cart. 

In the example, they are just pulling a single product to checkout, would it be possible to incorporate this into your example?  IE pulling from local storage/ all products that have been loaded into your cart from the various collections? 

I've tried implementing it, but haven't had success.  Please let me know if this is something you would be interested in taking a stab at. 

Possibly adding the following event listeners to the main SDK.js:

  ```
/* Bind Event Listeners
  ============================================================ */
  function bindEventListeners() {
    $('.cart .not-empty .btn.checkout').on('click', function () {
      var checkoutWindow = window.open(cart.checkoutUrl);
      window.addEventListener("message", checkoutPostMessageListener, checkoutWindow);
    });
  }

  /* Event Listener handles post messages from checkout page
  ============================================================ */
  function checkoutPostMessageListener(event) {
    var origin = event.origin || event.originalEvent.origin;
    if (origin !== 'https://checkout.shopify.com') {
      return;
    }

    var data = JSON.parse(event.data);
    
    if (data.current_checkout_page === '/checkout/thank_you') {
      cart.clearLineItems();
      completeUIRendering();

      // redirect to the home page or to custom thank you page.
    }


 **Let me know if you have any questions! Thanks!**

**Comment by ahl389** [comment]
@zstrad44 I'll try and check it out this weekend!

**Comment by ahl389** [comment]
Realize this was ages ago, but took a look at it just now.  Cart now clears after checkout - but the checkout window (which now opens in its own tab) doesn't redirect.  The real page will refresh with a cleared cart, though.
